// This file is generated by Slice Machine. Update with care!

import AlgoConImagen from './AlgoConImagen';
import OtraSlice from './OtraSlice';
import TextImageRight from './TextImageRight';

export {
	AlgoConImagen,
	OtraSlice,
	TextImageRight,
};

export const components = {
	algo_con_imagen: AlgoConImagen,
	otra_slice: OtraSlice,
	text_image_right: TextImageRight,
};
